### ISSUE TITLE
修复iOS上scroll-view组件内子元素设置z-index无效的问题。

### ISSUE THREAD

**Issue by vhvy** [vhvy/reminder#8]
由于iOS平台上scroll-view组件应用了` -webkit-overflow-scrolling: touch`这个属性，所以z-index属性受到了影响。

如果scroll-view组件内含有使用了定位属性的元素，那么在`scroll-view`元素上增加如下css即可：

```scss
.custom-scroll-view {
    ::v-deep .uni-scroll-view {
        -webkit-overflow-scrolling: auto;
    }
}
```
建议封装成组件后按需增加此css。

相关链接：
[https://developers.weixin.qq.com/community/develop/doc/0008ec653dcdc0eed419f70e751400](https://developers.weixin.qq.com/community/develop/doc/0008ec653dcdc0eed419f70e751400)
[https://blog.csdn.net/m0_37602317/article/details/116699808](https://blog.csdn.net/m0_37602317/article/details/116699808)
